-- MySQL Script generated by MySQL Workbench
-- Sun May  2 16:37:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`brand`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brand` ;

CREATE TABLE IF NOT EXISTS `mydb`.`brand` (
  `brand_id` INT NOT NULL,
  `brand_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`brand_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`size` ;

CREATE TABLE IF NOT EXISTS `mydb`.`size` (
  `size_id` INT NOT NULL,
  `size_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`size_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `product_id` INT NOT NULL,
  `product_name` VARCHAR(50) NOT NULL,
  `describe` VARCHAR(200) NOT NULL,
  `price` DECIMAL(6,2) NOT NULL,
  `lastday` DATE NOT NULL,
  `brand_id` INT NOT NULL,
  `size_id` INT NOT NULL,
  `has_topping_id` INT NOT NULL,
  PRIMARY KEY (`product_id`, `brand_id`, `size_id`, `has_topping_id`),
  UNIQUE INDEX `product_name_UNIQUE` (`product_name` ASC) VISIBLE,
  INDEX `fk_product_brand_idx` (`brand_id` ASC) VISIBLE,
  INDEX `fk_product_size2_idx` (`size_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_brand`
    FOREIGN KEY (`brand_id`)
    REFERENCES `mydb`.`brand` (`brand_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_size2`
    FOREIGN KEY (`size_id`)
    REFERENCES `mydb`.`size` (`size_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`topping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`topping` ;

CREATE TABLE IF NOT EXISTS `mydb`.`topping` (
  `topping_id` INT NOT NULL,
  `topping_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`topping_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_topping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_has_topping` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_has_topping` (
  `has_topping_id` INT NOT NULL,
  `topping_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  INDEX `fk_product_has_topping_topping1_idx` (`topping_id` ASC) VISIBLE,
  PRIMARY KEY (`has_topping_id`, `topping_id`, `product_id`),
  INDEX `fk_product_has_topping_product1_idx` (`product_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_topping_topping1`
    FOREIGN KEY (`topping_id`)
    REFERENCES `mydb`.`topping` (`topping_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_topping_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product_has_topping1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`product_has_topping1` ;

CREATE TABLE IF NOT EXISTS `mydb`.`product_has_topping1` (
  `product_product_code` INT NOT NULL,
  `product_brand_id` INT NOT NULL,
  `product_size_code` INT NOT NULL,
  `product_has_topping_id` INT NOT NULL,
  `topping_topping_id` INT NOT NULL,
  PRIMARY KEY (`product_product_code`, `product_brand_id`, `product_size_code`, `product_has_topping_id`, `topping_topping_id`),
  INDEX `fk_product_has_topping1_topping1_idx` (`topping_topping_id` ASC) VISIBLE,
  INDEX `fk_product_has_topping1_product1_idx` (`product_product_code` ASC, `product_brand_id` ASC, `product_size_code` ASC, `product_has_topping_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_has_topping1_product1`
    FOREIGN KEY (`product_product_code` , `product_brand_id` , `product_size_code` , `product_has_topping_id`)
    REFERENCES `mydb`.`product` (`product_id` , `brand_id` , `size_id` , `has_topping_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_has_topping1_topping1`
    FOREIGN KEY (`topping_topping_id`)
    REFERENCES `mydb`.`topping` (`topping_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `mydb`.`brand`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`brand` (`brand_id`, `brand_name`) VALUES (1001, 'Baskin Robbins');
INSERT INTO `mydb`.`brand` (`brand_id`, `brand_name`) VALUES (1002, 'Ben&Jerry’s');
INSERT INTO `mydb`.`brand` (`brand_id`, `brand_name`) VALUES (1003, 'Dairy Queen');
INSERT INTO `mydb`.`brand` (`brand_id`, `brand_name`) VALUES (1004, 'Suzukien');
INSERT INTO `mydb`.`brand` (`brand_id`, `brand_name`) VALUES (1005, 'Swensens');
INSERT INTO `mydb`.`brand` (`brand_id`, `brand_name`) VALUES (1006, 'Umm Milk');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`size`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`size` (`size_id`, `size_type`) VALUES (2001, 'S');
INSERT INTO `mydb`.`size` (`size_id`, `size_type`) VALUES (2002, 'M');
INSERT INTO `mydb`.`size` (`size_id`, `size_type`) VALUES (2003, 'L');
INSERT INTO `mydb`.`size` (`size_id`, `size_type`) VALUES (2004, 'XL');

COMMIT;


-- -----------------------------------------------------
-- Data for table `mydb`.`topping`
-- -----------------------------------------------------
START TRANSACTION;
USE `mydb`;
INSERT INTO `mydb`.`topping` (`topping_id`, `topping_name`) VALUES (3001, 'Almond');
INSERT INTO `mydb`.`topping` (`topping_id`, `topping_name`) VALUES (3002, 'Brownie');
INSERT INTO `mydb`.`topping` (`topping_id`, `topping_name`) VALUES (3003, 'Chocolate ball');
INSERT INTO `mydb`.`topping` (`topping_id`, `topping_name`) VALUES (3004, 'Chocolate chip');
INSERT INTO `mydb`.`topping` (`topping_id`, `topping_name`) VALUES (3005, 'Cookie crumble');
INSERT INTO `mydb`.`topping` (`topping_id`, `topping_name`) VALUES (3006, 'Oreo');
INSERT INTO `mydb`.`topping` (`topping_id`, `topping_name`) VALUES (3007, 'Rainbow');
INSERT INTO `mydb`.`topping` (`topping_id`, `topping_name`) VALUES (3008, 'Sticky rice');

COMMIT;

