CREATE USER 'pin'@'%' IDENTIFIED BY 'Coolcream04';
CREATE USER 'nooch'@'%' IDENTIFIED BY 'Coolcream47';
CREATE USER 'nook'@'%' IDENTIFIED BY 'Coolcream52';

GRANT ALL ON *.* TO `nook`@`%` WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROLE, DROP ROLE ON *.* TO `nooch`@`%` WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROLE, DROP ROLE ON *.* TO `pin`@`%` WITH GRANT OPTION;

commit;