CREATE USER 'member'@'%' IDENTIFIED BY 'Coolcream';
CREATE USER 'owner'@'%' IDENTIFIED BY 'Coolcream044752';

GRANT ALL ON *.* TO `owner`@`%` WITH GRANT OPTION;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, EXECUTE, CREATE VIEW, SHOW VIEW, CREATE ROLE, DROP ROLE ON *.* TO `member`@`%`;

commit;